name: Client Generation
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Generate-Python-Client:
    runs-on: ubuntu-latest
    steps:
    - name: Make spec directory
      run: mkdir public
    - name: Download spec file
      run: curl https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml -o public/DigitalOcean-public.v2.yaml
    - uses: actions/upload-artifact@v2
      with:
        name: DigitalOcean-public.v2
        path: public/DigitalOcean-public.v2.yaml
    - name: install autorest
      run: npm install -g autorest
    - name: generate code
      run: autorest --input-file=public/DigitalOcean-public.v2.yaml --python --output-folder=do-client-python/ 
    - uses: actions/checkout@v3
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.PY_CLIENT }}
        commit-message: Re-generate Python Client
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: bot-regenerate-python-client
        delete-branch: true
        title: '[Bot] Re-generate Python Client'
        body: |
          Re-generate Python Client
          - Changes to DigitalOcean spec triggered this regeneration of the python client.
          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: |
          automated pr
        team-reviewers: |
          owners
          maintainers
        draft: false