name: Client Generation
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  Generate-Python-Client:
    runs-on: ubuntu-latest
    steps:
    - name: Make spec directory
      run: mkdir public
    - name: Download spec file
      run: curl https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.yaml -o public/DigitalOcean-public.v2.yaml
    - uses: actions/upload-artifact@v2
      with:
        name: DigitalOcean-public.v2
        path: public/DigitalOcean-public.v2.yaml
    - name: install autorest
      run: npm install -g autorest
    - name: generate code
      run: autorest --input-file=public/DigitalOcean-public.v2.yaml --python --output-folder=do-client-python/ 